issue/#247-lisaa-pre-commit-hook * update pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -10,6 +10,12 @@ STAGED_FRONTEND_FILES=$(git diff --cached --name-only --relative frontend | grep
 if [ -n "$STAGED_FRONTEND_FILES" ]; then
     for file in $STAGED_FRONTEND_FILES; do
         npx prettier --write "$file"
+
+        if [ $? -ne 0 ]; then
+            echo "Error: Prettier formatting failed for $file. Commit aborted."
+            exit 1
+        fi
+
         git add "$file"
     done
 fi
@@ -20,6 +26,11 @@ STAGED_BACKEND_FILES=$(git diff --cached --name-only --relative backend | grep -
 # Format staged backend files with Spotless and re-stage formatted files
 if [ -n "$STAGED_BACKEND_FILES" ]; then
     ./backend/gradlew -p backend spotlessApply
+
+    if [ $? -ne 0 ]; then
+        echo "Error: Spotless formatting failed. Commit aborted."
+        exit 1
+    fi
 
     for file in $STAGED_BACKEND_FILES; do
         git add "$file"
